# Improved code generated by AI agent

def greet_users(names):
    """Greets a list of users by name."""
    for name in names:
        print("Hello " + name)


def find_even_numbers(numbers):
    """Returns a list of even numbers from the input list."""
    even_numbers = []
    for num in numbers:
        if num % 2 == 0:
            even_numbers.append(num)
    return even_numbers


# Example usage
names = ["Alice", "Bob", "Charlie"]
numbers = [1, 2, 3, 4, 5, 6]

greet_users(names)
print(find_even_numbers(numbers))
